default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sabalas-dev
  username: root
  password: password

test:
  <<: *default
  database: sabalas-test
  username: root
  password: password

production:
  <<: *default
  database: sabalas
